package com.cryptoai.overlay

import okhttp3.*
import org.json.JSONArray
import org.json.JSONObject
import java.time.Instant
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import kotlin.math.*

class AllPairsScanner {
    data class HorizonPlan(val minutes:Int,val target:Double,val stop:Double,val score:Int,val net:Double,val rr:Double,val entry:Double,val slip:Double,val valid:Boolean)
    data class Pick(val product:String,val price:Double,val rsi:Double,val atr:Double,val history30d:Double,val plans:Map<Int,HorizonPlan>)
    data class Result(val scannedPairs:Int,val detailedPairs:Int,val amount:Double,val best1:Pick?,val best5:Pick?,val best15:Pick?,val suggestedProduct:String?,val suggestedWindow:Int?,val top:List<Pick>,val note:String)
    private data class Product(val id:String)
    private data class Ticker(val id:String,val price:Double,val bid:Double,val ask:Double,val volume:Double,val change:Double)
    private data class Level(val p:Double,val q:Double)
    private data class Book(val asks:List<Level>,val mid:Double,val ask:Double,val spread:Double,val imbalance:Double,val depth:Double,val support:Double,val resistance:Double)
    private data class Candle(val rsi:Double,val atr:Double,val t1:Double,val t5:Double,val t15:Double)
    private data class Hist(val r24:Double,val r7:Double,val r30:Double,val abs90:Double,val expansion:Double)
    private val http=OkHttpClient.Builder().pingInterval(20,TimeUnit.SECONDS).build()
    private val fee=.006
    @Volatile private var stopped=false
    private var ws:WebSocket?=null
    fun stop(){stopped=true;try{ws?.close(1000,"stop")}catch(_:Exception){}}

    fun scan(amount:Double,progress:(String)->Unit={},done:(Result)->Unit){Thread{
        val bank=amount.coerceAtLeast(1.0)
        try{
            stopped=false;progress("Loading every live Coinbase USD pair…")
            val products=products();val ticks=tickers(products);if(stopped)return@Thread
            val finalists=pre(products,ticks).take(14);val picks=mutableListOf<Pick>()
            finalists.forEachIndexed{i,t->if(stopped)return@Thread;progress("Checking ${i+1}/${finalists.size}: ${t.id}");try{analyze(t,bank)?.let{picks+=it}}catch(_:Exception){};Thread.sleep(150)}
            fun best(m:Int)=picks.maxWithOrNull(compareBy<Pick>{it.plans[m]?.score?:0}.thenBy{it.plans[m]?.net?:-999.0})
            val b1=best(1);val b5=best(5);val b15=best(15)
            val good=listOf(1 to b1,5 to b5,15 to b15).mapNotNull{(m,p)->val hp=p?.plans?.get(m)?:return@mapNotNull null;if(hp.valid&&hp.net>0&&hp.score>=55&&hp.rr>=.85)Triple(m,p,hp)else null}
            val win=good.maxWithOrNull(compareBy<Triple<Int,Pick,HorizonPlan>>{it.third.score}.thenBy{it.third.net})
            val note=if(win==null)"No clean positive-profit setup for $${money(bank)} right now after fees, visible liquidity and slippage." else "${win.second.product} is the strongest current ${win.first}m setup for $${money(bank)}."
            done(Result(products.size,picks.size,bank,b1,b5,b15,win?.second?.product,win?.first,picks.sortedByDescending{it.plans.values.maxOfOrNull{p->p.score}?:0}.take(6),note))
        }catch(e:Exception){done(Result(0,0,bank,null,null,null,null,null,emptyList(),"Scan error: ${e.message?:"unknown"}"))}
    }.start()}

    private fun money(v:Double)=if(v%1.0==0.0)String.format("%.0f",v)else String.format("%.2f",v)
    private fun json(url:String):Any=http.newCall(Request.Builder().url(url).header("User-Agent","TwistedPsycheCrypto/0.8").build()).execute().use{r->if(!r.isSuccessful)error("HTTP ${r.code}");val s=r.body?.string().orEmpty();if(s.trim().startsWith("["))JSONArray(s)else JSONObject(s)}
    private fun products():List<Product>{val a=json("https://api.exchange.coinbase.com/products") as JSONArray;return(0 until a.length()).mapNotNull{i->val p=a.getJSONObject(i);if(p.optString("quote_currency")=="USD"&&p.optString("status")=="online"&&!p.optBoolean("trading_disabled")&&!p.optBoolean("cancel_only")&&!p.optBoolean("post_only"))Product(p.optString("id"))else null}}
    private fun tickers(ps:List<Product>):Map<String,Ticker>{val out=java.util.concurrent.ConcurrentHashMap<String,Ticker>();val open=CountDownLatch(1);ws=http.newWebSocket(Request.Builder().url("wss://advanced-trade-ws.coinbase.com").build(),object:WebSocketListener(){override fun onOpen(w:WebSocket,r:Response){open.countDown();ps.map{it.id}.chunked(75).forEach{w.send(JSONObject().put("type","subscribe").put("channel","ticker").put("product_ids",JSONArray(it)).toString())}};override fun onMessage(w:WebSocket,text:String){try{val e=JSONObject(text).optJSONArray("events")?:return;for(i in 0 until e.length()){val ts=e.getJSONObject(i).optJSONArray("tickers")?:continue;for(k in 0 until ts.length()){val t=ts.getJSONObject(k);val id=t.optString("product_id");val px=t.optString("price").toDoubleOrNull()?:0.0;val bid=t.optString("best_bid").toDoubleOrNull()?:0.0;val ask=t.optString("best_ask").toDoubleOrNull()?:0.0;val vol=t.optString("volume_24_h").toDoubleOrNull()?:0.0;val ch=(t.optString("price_percent_chg_24_h").toDoubleOrNull()?:0.0)/100;if(id.isNotBlank()&&px>0)out[id]=Ticker(id,px,bid,ask,vol,ch)}}}catch(_:Exception){}}});open.await(3,TimeUnit.SECONDS);val until=System.currentTimeMillis()+6500;while(System.currentTimeMillis()<until&&!stopped){Thread.sleep(300);if(out.size>=(ps.size*.7).toInt().coerceAtLeast(40))break};try{ws?.close(1000,"done")}catch(_:Exception){};return out}
    private fun pre(ps:List<Product>,m:Map<String,Ticker>)=ps.mapNotNull{m[it.id]}.filter{t->val mid=if(t.bid>0&&t.ask>=t.bid)(t.bid+t.ask)/2 else t.price;val sp=if(t.bid>0&&t.ask>=t.bid)(t.ask-t.bid)/mid else .02;t.price*max(0.0,t.volume)>=25000&&sp<=.012}.sortedByDescending{t->val mid=if(t.bid>0&&t.ask>=t.bid)(t.bid+t.ask)/2 else t.price;val sp=if(t.bid>0&&t.ask>=t.bid)(t.ask-t.bid)/mid else .02;val q=t.price*max(0.0,t.volume);.55*((log10(q+1)-4.4)/3.4).coerceIn(0.0,1.0)+.22*(abs(t.change)/.12).coerceIn(0.0,1.0)+.23*(1-sp/.012).coerceIn(0.0,1.0)}
    private fun analyze(t:Ticker,bank:Double):Pick?{val id=t.id;val b=book(json("https://api.exchange.coinbase.com/products/$id/book?level=2") as JSONObject)?:return null;val c=candles(json("https://api.exchange.coinbase.com/products/$id/candles?granularity=60") as JSONArray)?:return null;val h=history(id);val quality=(.45*(1-b.spread/.008).coerceIn(0.0,1.0)+.35*((log10(b.depth+1)-3.5)/3.0).coerceIn(0.0,1.0)+.20*(if(c.rsi in 20.0..80.0)1.0 else .7)).coerceIn(0.0,1.0);val plans=linkedMapOf<Int,HorizonPlan>();for(mins in listOf(1,5,15)){val d=dir(mins,b,c,t,h);val target=target(mins,b,c,d,quality,h);val stop=b.support.coerceAtMost(b.mid*(1-if(mins==1).0025 else .005));val p=plan(bank,b,target,stop);val strength=abs(d)*100*quality;val score=if(!p.valid||d<=.10)0 else (strength*.55+quality*20+(p.rr/2).coerceIn(0.0,1.0)*15+if(p.net>0)10 else -25-(p.slip/.01).coerceIn(0.0,1.0)*15).roundToInt().coerceIn(0,100);plans[mins]=HorizonPlan(mins,target,stop,score,p.net,p.rr,p.entry,p.slip,p.valid)};return Pick(id,b.mid,c.rsi,c.atr,h?.r30?:0.0,plans)}
    private data class Plan(val valid:Boolean,val net:Double,val rr:Double,val entry:Double,val slip:Double)
    private fun plan(bank:Double,b:Book,target:Double,stop:Double):Plan{val budget=bank/(1+fee);var rem=budget;var cost=0.0;var qty=0.0;for(l in b.asks){val cap=l.p*l.q;val take=min(rem,cap);qty+=take/l.p;cost+=take;rem-=take;if(rem<=1e-7)break};if(rem>max(.01,budget*.001)||qty<=0)return Plan(false,-999.0,-99.0,0.0,1.0);val entry=cost/qty;val slip=max(0.0,(entry-b.ask)/b.ask);val drag=max(b.spread/2,slip*.7);val net=qty*target*(1-drag)*(1-fee)-bank;val loss=max(0.0,bank-qty*stop*(1-drag)*(1-fee));return Plan(true,net,if(loss>0)net/loss else 0.0,entry,slip)}
    private fun dir(m:Int,b:Book,c:Candle,t:Ticker,h:Hist?):Double{fun cl(v:Double)=v.coerceIn(-1.0,1.0);val r=cl((c.rsi-50)/35);val h24=cl((h?.r24?:0.0)/.08);val h7=cl((h?.r7?:0.0)/.18);val h30=cl((h?.r30?:0.0)/.35);return when(m){1->cl(.48*b.imbalance+.27*cl(c.t1/.004)+.15*r+.10*h24);5->cl(.36*b.imbalance+.24*cl(c.t5/.012)+.12*cl(c.t15/.025)+.10*r+.10*h24+.08*h7);else->cl(.24*b.imbalance+.18*cl(c.t5/.012)+.20*cl(c.t15/.025)+.08*r+.12*h24+.12*h7+.06*h30)}}
    private fun target(m:Int,b:Book,c:Candle,d:Double,q:Double,h:Hist?):Double{val tr=if(m==1)c.t1 else if(m==5)c.t5 else c.t15;val floor=if(m==1).0007 else if(m==5).0015 else .003;val cap=if(m==1).018 else if(m==5).04 else .075;val hist=(h?.abs90?:0.0)*sqrt(m/60.0)*(h?.expansion?:1.0).coerceIn(.65,2.2);val move=max(floor,max(c.atr*sqrt(m.toDouble())*.68,max(abs(tr)*.58,hist*.75)))*(.52+max(0.0,d)*1.08)*(.8+q*.42);return min(b.mid*(1+move.coerceIn(floor*.7,cap)),if(b.resistance>b.mid)b.resistance else Double.MAX_VALUE)}
    private fun book(j:JSONObject):Book?{fun lv(n:String)=j.optJSONArray(n)?.let{a->(0 until min(120,a.length())).mapNotNull{i->val x=a.optJSONArray(i)?:return@mapNotNull null;val p=x.optString(0).toDoubleOrNull()?:0.0;val q=x.optString(1).toDoubleOrNull()?:0.0;if(p>0&&q>0)Level(p,q)else null}}?:emptyList();val bids=lv("bids");val asks=lv("asks");if(bids.isEmpty()||asks.isEmpty())return null;val bid=bids.first().p;val ask=asks.first().p;val mid=(bid+ask)/2;val bd=bids.take(50).sumOf{it.p*it.q};val ad=asks.take(50).sumOf{it.p*it.q};val sup=bids.filter{it.p>=mid*.985}.maxByOrNull{it.p*it.q}?.p?:bid;val res=asks.filter{it.p<=mid*1.015}.maxByOrNull{it.p*it.q}?.p?:ask;return Book(asks,mid,ask,(ask-bid)/mid,(bd-ad)/(bd+ad).coerceAtLeast(1e-9),bd+ad,sup,res)}
    private fun candles(a:JSONArray):Candle?{data class C(val t:Long,val l:Double,val h:Double,val c:Double);val r=(0 until a.length()).mapNotNull{i->val x=a.optJSONArray(i)?:return@mapNotNull null;val c=x.optDouble(4);if(c>0)C(x.optLong(0),x.optDouble(1),x.optDouble(2),c)else null}.sortedBy{it.t};if(r.size<20)return null;val cl=r.map{it.c};val last=cl.last();fun tr(n:Int):Double{val b=cl[(cl.size-1-n).coerceAtLeast(0)];return if(b>0)(last-b)/b else 0.0};var g=0.0;var l=0.0;for(i in cl.size-14 until cl.size){val d=cl[i]-cl[i-1];if(d>=0)g+=d else l-=d};val rsi=if(l==0.0)100.0 else 100-100/(1+(g/14)/(l/14));var x=0.0;for(i in r.size-14 until r.size){val p=r[i-1].c;x+=max(r[i].h-r[i].l,max(abs(r[i].h-p),abs(r[i].l-p)))};return Candle(rsi,(x/14)/last,tr(1),tr(5),tr(15))}
    private fun history(id:String):Hist?{val now=System.currentTimeMillis()/1000;val all=mutableListOf<JSONArray>();for(k in 3 downTo 1){val s=now-k*10*86400;val e=s+10*86400;try{val a=json("https://api.exchange.coinbase.com/products/$id/candles?granularity=3600&start=${Instant.ofEpochSecond(s)}&end=${Instant.ofEpochSecond(e)}") as JSONArray;for(i in 0 until a.length())all+=a.getJSONArray(i)}catch(_:Exception){}};if(all.size<72)return null;val rows=all.distinctBy{it.optLong(0)}.sortedBy{it.optLong(0)};val cl=rows.map{it.optDouble(4)};fun ret(n:Int):Double{val b=cl[(cl.size-1-n).coerceAtLeast(0)];return if(b>0)(cl.last()-b)/b else 0.0};val rs=(1 until cl.size).map{i->if(cl[i-1]>0)(cl[i]-cl[i-1])/cl[i-1] else 0.0};val av=rs.map{v->abs(v)}.sorted();val p90=av[((av.size-1)*.9).toInt()];val recent=rs.takeLast(24).map{v->abs(v)}.average();val old=rs.dropLast(24).takeLast(336).map{v->abs(v)};val older=if(old.isEmpty())recent else old.average();return Hist(ret(24),ret(168),ret(min(719,cl.size-1)),p90,if(older>0)recent/older else 1.0)}
}
