let sockets=[],running=false,bank=50;
const bids=new Map(),asks=new Map(),trades=[];
const venue={Coinbase:null,Kraken:null,OKX:null,Binance:null};
const $=id=>document.getElementById(id);
const fmt=n=>!n||!isFinite(n)?'—':n<1?n.toFixed(6):n.toFixed(2);
const money=n=>'$'+Math.abs(n).toFixed(2);
function closeAll(){running=false;sockets.forEach(s=>{try{s.close()}catch{}});sockets=[];bids.clear();asks.clear();trades.length=0;}
function open(url,onOpen,onMsg){const s=new WebSocket(url);s.onopen=()=>onOpen&&onOpen(s);s.onmessage=e=>onMsg&&onMsg(e.data);s.onerror=()=>{};sockets.push(s);}
function setVenue(name,b,a){b=+b;a=+a;if(b>0&&a>=b)venue[name]={bid:b,ask:a,t:Date.now()};}
function start(){closeAll();running=true;const product=$('pair').value.trim().toUpperCase()||'BTC-USD';const [base,rawQuote='USD']=product.split('-');const quote=rawQuote.toUpperCase();
open('wss://advanced-trade-ws.coinbase.com',s=>['level2','market_trades','heartbeats'].forEach(channel=>s.send(JSON.stringify({type:'subscribe',product_ids:[product],channel}))),txt=>{try{const j=JSON.parse(txt);for(const e of j.events||[]){if(j.channel==='l2_data'){for(const u of e.updates||[]){const p=+u.price_level,q=+u.new_quantity,m=u.side==='bid'?bids:asks;if(p>0){if(q===0)m.delete(p);else m.set(p,q);}}}if(j.channel==='market_trades'){for(const t of e.trades||[])trades.push({t:Date.now(),q:+t.size,buy:String(t.side).toUpperCase()==='SELL'});}}emit(product);}catch{}});
const kraken=`${base}/${quote==='USDC'?'USD':quote}`;open('wss://ws.kraken.com/v2',s=>s.send(JSON.stringify({method:'subscribe',params:{channel:'ticker',symbol:[kraken],snapshot:true}})),txt=>{try{const j=JSON.parse(txt),d=j.data?.[0];if(j.channel==='ticker'&&d){setVenue('Kraken',d.bid,d.ask);emit(product)}}catch{}});
const okx=`${base}-${quote==='USD'?'USDT':quote}`;open('wss://ws.okx.com:8443/ws/v5/public',s=>s.send(JSON.stringify({op:'subscribe',args:[{channel:'tickers',instId:okx}]})),txt=>{try{const d=JSON.parse(txt).data?.[0];if(d){setVenue('OKX',d.bidPx,d.askPx);emit(product)}}catch{}});
const binance=(base+(quote==='USD'?'USDT':quote)).toLowerCase();open(`wss://stream.binance.com:9443/ws/${binance}@bookTicker`,null,txt=>{try{const j=JSON.parse(txt);setVenue('Binance',j.b,j.a);emit(product)}catch{}});
}
function emit(product){if(!running||!bids.size||!asks.size)return;const b=[...bids.keys()].sort((x,y)=>y-x),a=[...asks.keys()].sort((x,y)=>x-y);const bid=b[0],ask=a[0],mid=(bid+ask)/2;setVenue('Coinbase',bid,ask);const now=Date.now();while(trades.length&&now-trades[0].t>10000)trades.shift();const depth=.006;const bd=b.filter(p=>p>=mid*(1-depth)).reduce((s,p)=>s+(bids.get(p)||0),0);const ad=a.filter(p=>p<=mid*(1+depth)).reduce((s,p)=>s+(asks.get(p)||0),0);const imb=(bd-ad)/(bd+ad||1);const buy=trades.filter(t=>t.buy).reduce((s,t)=>s+t.q,0);const sell=trades.filter(t=>!t.buy).reduce((s,t)=>s+t.q,0);const flow=(buy-sell)/(buy+sell||1);const bestB=bids.get(bid)||0,bestA=asks.get(ask)||0,micro=(bestB-bestA)/(bestB+bestA||1);let sources=0,venueScore=0;for(const [name,v] of Object.entries(venue)){if(v&&now-v.t<15000){sources++;if(name!=='Coinbase')venueScore+=((v.bid+v.ask)/2-mid)/mid;}}venueScore=Math.max(-1,Math.min(1,venueScore*20));const spread=(ask-bid)/mid;let score=.45*imb+.35*flow+.10*micro+.10*venueScore;if(spread>.004)score*=.45;score=Math.max(-1,Math.min(1,score));const conf=Math.min(95,Math.round(Math.abs(score)*100*(sources>=3?1.08:sources===1?.82:1)));const range=Math.max(ask-bid,mid*.0015);const support=b.slice(0,40).sort((x,y)=>(bids.get(y)||0)-(bids.get(x)||0))[0]||bid;const resistance=a.slice(0,40).sort((x,y)=>(asks.get(y)||0)-(asks.get(x)||0))[0]||ask;const buyLow=Math.min(ask,Math.max(support,mid-range*2));const target=Math.max(mid+range*4,resistance>ask?resistance:0);const stop=Math.max(0,Math.min(mid-range*3,support-range*.75));let signal='WAIT';if(spread>.004)signal='WAIT — SPREAD TOO WIDE';else if(score>=.36&&conf>=45)signal='BUY NOW';else if(score<=-.36&&conf>=45)signal='SELL NOW';else if(score>=.18)signal='GET READY TO BUY';else if(score<=-.18)signal='GET READY TO SELL';let reason=Math.abs(imb)>.15?(imb>0?'buyers heavier in book':'sellers heavier in book'):'no strong book edge';if(Math.abs(flow)>.15)reason+=' • '+(flow>0?'buyers hitting market':'selling pressure');if(sources>=3)reason+=' • other exchanges connected';render({mid,ask,buyLow,target,stop,signal,conf,sources,reason});}
function render(m){$('signal').textContent=m.signal;$('reason').textContent=m.reason;$('price').textContent=fmt(m.mid);$('buy').textContent=`${fmt(m.buyLow)} – ${fmt(m.ask)}`;$('target').textContent=fmt(m.target);$('stoppx').textContent=fmt(m.stop);$('conf').textContent=m.conf+'%';$('feeds').textContent=m.sources+'/4 live';const fee=.006,spend=bank,entry=m.ask,buyFee=spend*fee,usable=spend-buyFee,tokens=usable/entry,gross=tokens*m.target,sellFee=gross*fee,net=gross-sellFee-spend,stopGross=tokens*m.stop,stopFee=stopGross*fee,loss=spend-(stopGross-stopFee),be=spend/(tokens*(1-fee)),rr=loss>0?net/loss:0;$('bankLabel').textContent='$'+spend.toFixed(2);$('tokens').textContent=tokens.toFixed(6);$('buyfee').textContent=money(buyFee);$('breakeven').textContent=fmt(be);$('sellfee').textContent=money(sellFee);$('profit').textContent=(net>=0?'+':'-')+money(net);$('loss').textContent='-'+money(loss);$('rr').textContent=isFinite(rr)?rr.toFixed(2)+':1':'—';let d=m.signal;if(m.signal.includes('BUY')){if(net<=0)d='WAIT — PROFIT TOO SMALL AFTER FEES';else if(rr<1)d='WAIT — SETUP NOT WORTH THE RISK';}$('decision').textContent=d;$('decision').className='big '+(d.startsWith('BUY')?'good':d.startsWith('SELL')?'bad':'warn');}
$('start').onclick=start;$('stop').onclick=()=>{closeAll();$('signal').textContent='STOPPED';$('reason').textContent='Market feeds closed.'};document.querySelectorAll('.bank').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.bank').forEach(x=>x.classList.remove('active'));btn.classList.add('active');bank=+btn.dataset.bank;$('custom').value='';});$('custom').oninput=e=>{const v=+e.target.value;if(v>0){bank=v;document.querySelectorAll('.bank').forEach(x=>x.classList.remove('active'));}};$('acctToggle').onclick=()=>$('acct').classList.toggle('hidden');