(()=>{
  const $s=id=>document.getElementById(id);
  const API='https://api.exchange.coinbase.com',WS='wss://advanced-trade-ws.coinbase.com';
  const FEE=.006,DETAIL_COUNT=14;
  const tickers=new Map(),monthCache=new Map(),hourCache=new Map();
  let products=[],sock=null,scanning=false,lastDetailed=0,refreshTimer=null,lastRows=[],historyWarm=false;
  const sleep=ms=>new Promise(r=>setTimeout(r,ms)),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
  const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
  const percentile=(a,p)=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),i=Math.min(s.length-1,Math.max(0,Math.floor((s.length-1)*p)));return s[i]};
  const money=n=>Number.isFinite(n)?`${n>=0?'+':'-'}$${Math.abs(n).toFixed(2)}`:'—';
  const px=n=>{if(!Number.isFinite(n)||n<=0)return'—';const d=clamp(7-Math.floor(Math.log10(Math.abs(n))),2,12);return n.toFixed(d)};
  const pct=n=>Number.isFinite(n)?`${n>=0?'+':''}${(n*100).toFixed(2)}%`:'—';
  async function jfetch(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
  function setStatus(text,cls='warn'){const el=$s('scanStatus');if(el){el.textContent=text;el.className='signal '+cls}}
  function selectedAmount(){const custom=+$s('custom')?.value;if(custom>0)return custom;const active=document.querySelector('.bank.active');return +(active?.dataset.bank||50)}
  function amountLabel(n){return '$'+Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}

  async function loadProducts(){const rows=await jfetch(`${API}/products`);products=rows.filter(p=>p.quote_currency==='USD'&&p.status==='online'&&!p.trading_disabled&&!p.cancel_only&&!p.post_only);if($s('scanUniverse'))$s('scanUniverse').textContent=`${products.length} live Coinbase USD pairs`;return products}
  function closeSocket(){if(sock){try{sock.close()}catch{}sock=null}}
  function openTickerSocket(){closeSocket();tickers.clear();sock=new WebSocket(WS);sock.onopen=()=>{const ids=products.map(p=>p.id);for(let i=0;i<ids.length;i+=75)sock.send(JSON.stringify({type:'subscribe',channel:'ticker',product_ids:ids.slice(i,i+75)}))};sock.onmessage=e=>{try{const j=JSON.parse(e.data);for(const ev of j.events||[])for(const t of ev.tickers||[]){const price=+t.price,bid=+t.best_bid,ask=+t.best_ask,vol=+t.volume_24_h,chg=(+t.price_percent_chg_24_h||0)/100;if(price>0)tickers.set(t.product_id,{id:t.product_id,price,bid,ask,vol,chg,t:Date.now()})}}catch{}};sock.onerror=()=>setStatus('SCANNER CONNECTION PROBLEM — retrying','bad');sock.onclose=()=>{if(products.length)setTimeout(()=>{if(!sock||sock.readyState===WebSocket.CLOSED)openTickerSocket()},2500)}}

  function dailyHistoryMetrics(raw){const c=(raw||[]).map(x=>({t:+x[0],c:+x[4],h:+x[2],l:+x[1]})).sort((a,b)=>a.t-b.t);if(c.length<10)return null;const last=c.at(-1).c,first=c[0].c,rets=[];for(let i=1;i<c.length;i++)rets.push((c[i].c-c[i-1].c)/c[i-1].c);return{ret30:first>0?(last-first)/first:0,upFreq:rets.filter(x=>x>0).length/(rets.length||1),dailyAbs90:percentile(rets.map(Math.abs),.90),range30:(Math.max(...c.map(x=>x.h))-Math.min(...c.map(x=>x.l)))/last,bars:c.length}}
  async function fetchMonthDaily(id){const hit=monthCache.get(id);if(hit&&Date.now()-hit.t<6*3600000)return hit.v;const end=Math.floor(Date.now()/1000),start=end-32*86400;try{const raw=await jfetch(`${API}/products/${encodeURIComponent(id)}/candles?granularity=86400&start=${new Date(start*1000).toISOString()}&end=${new Date(end*1000).toISOString()}`),v=dailyHistoryMetrics(raw);if(v)monthCache.set(id,{t:Date.now(),v});return v}catch{return null}}
  async function warmHistoryUniverse(){if(historyWarm)return;historyWarm=true;let done=0;for(const p of products){if(monthCache.has(p.id)){done++;continue}await fetchMonthDaily(p.id);done++;if($s('historyCoverage'))$s('historyCoverage').textContent=`${done}/${products.length} pairs have 30-day history`;await sleep(140)}if($s('historyCoverage'))$s('historyCoverage').textContent=`${done}/${products.length} pairs cached for 30-day history`}

  async function fetchHourly30(id){const hit=hourCache.get(id);if(hit&&Date.now()-hit.t<30*60000)return hit.v;const now=Math.floor(Date.now()/1000),all=[];for(let k=3;k>0;k--){const start=now-k*10*86400,end=start+10*86400;try{const r=await jfetch(`${API}/products/${encodeURIComponent(id)}/candles?granularity=3600&start=${new Date(start*1000).toISOString()}&end=${new Date(end*1000).toISOString()}`);all.push(...r)}catch{}await sleep(80)}const map=new Map();for(const x of all)map.set(+x[0],x);const c=[...map.values()].map(x=>({t:+x[0],l:+x[1],h:+x[2],o:+x[3],c:+x[4],v:+x[5]})).sort((a,b)=>a.t-b.t);if(c.length<72)return null;const close=c.map(x=>x.c),last=close.at(-1),ret=(bars)=>{const i=Math.max(0,close.length-1-bars),b=close[i];return b>0?(last-b)/b:0},r=[];for(let i=1;i<close.length;i++)r.push((close[i]-close[i-1])/close[i-1]);const recent=r.slice(-24),old=r.slice(Math.max(0,r.length-24*14),-24),v={ret24:ret(24),ret7d:ret(168),ret30d:ret(Math.min(719,close.length-1)),hourAbs50:percentile(r.map(Math.abs),.50),hourAbs90:percentile(r.map(Math.abs),.90),recentAbs:avg(recent.map(Math.abs)),olderAbs:avg(old.map(Math.abs)),expansion:avg(old.map(Math.abs))>0?avg(recent.map(Math.abs))/avg(old.map(Math.abs)):1,upFreq:r.filter(x=>x>0).length/(r.length||1),bars:c.length};hourCache.set(id,{t:Date.now(),v});return v}

  function preCandidates(){const now=Date.now(),rows=[];for(const p of products){const t=tickers.get(p.id);if(!t||now-t.t>45000)continue;const mid=(t.bid>0&&t.ask>=t.bid)?(t.bid+t.ask)/2:t.price,spread=t.bid>0&&t.ask>=t.bid?(t.ask-t.bid)/mid:.02,quoteVol=t.price*Math.max(0,t.vol);if(quoteVol<25000||spread>.012)continue;const mh=monthCache.get(p.id)?.v,liq=clamp((Math.log10(quoteVol+1)-4.4)/3.4,0,1),motion=clamp(Math.abs(t.chg)/.12,0,1),spreadQ=clamp(1-spread/.012,0,1),histMove=mh?clamp(mh.dailyAbs90/.08,0,1):.35,histBias=mh?clamp((mh.upFreq-.5)*2,-1,1):0;rows.push({...t,quoteVol,spread,pre:.45*liq+.20*motion+.18*spreadQ+.12*histMove+.05*Math.max(0,histBias)})}return rows.sort((a,b)=>b.pre-a.pre).slice(0,DETAIL_COUNT)}
  function candleMetrics(raw){const c=(raw||[]).map(x=>({t:+x[0],l:+x[1],h:+x[2],o:+x[3],c:+x[4],v:+x[5]})).sort((a,b)=>a.t-b.t);if(c.length<20)return null;const last=c.at(-1),close=c.map(x=>x.c),tr=n=>(last.c-close[Math.max(0,close.length-1-n)])/close[Math.max(0,close.length-1-n)];let gains=0,losses=0;for(let i=close.length-14;i<close.length;i++){const d=close[i]-close[i-1];if(d>=0)gains+=d;else losses-=d}const rsi=losses===0?100:100-100/(1+(gains/14)/(losses/14));let trueRange=0;for(let i=c.length-14;i<c.length;i++)trueRange+=Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c));return{last:last.c,trend1:tr(1),trend5:tr(5),trend15:tr(15),rsi,atr:(trueRange/14)/last.c}}
  function bookMetrics(j){const bids=(j.bids||[]).slice(0,120).map(x=>({p:+x[0],q:+x[1]})).filter(x=>x.p>0&&x.q>0),asks=(j.asks||[]).slice(0,120).map(x=>({p:+x[0],q:+x[1]})).filter(x=>x.p>0&&x.q>0);if(!bids.length||!asks.length)return null;const bid=bids[0].p,ask=asks[0].p,mid=(bid+ask)/2,spread=(ask-bid)/mid,bn=bids.slice(0,50).map(x=>x.p*x.q),an=asks.slice(0,50).map(x=>x.p*x.q),bd=bn.reduce((s,x)=>s+x,0),ad=an.reduce((s,x)=>s+x,0),imb=(bd-ad)/(bd+ad||1),top5=(bn.slice(0,5).reduce((s,x)=>s+x,0)+an.slice(0,5).reduce((s,x)=>s+x,0))/(bd+ad||1),medB=median(bn),medA=median(an),support=bids.filter(x=>x.p>=mid*.985).sort((a,b)=>(b.p*b.q)-(a.p*a.q))[0]||bids[0],resistance=asks.filter(x=>x.p<=mid*1.015).sort((a,b)=>(b.p*b.q)-(a.p*a.q))[0]||asks[0];return{bids,asks,bid,ask,mid,spread,imb,top5,depth:bd+ad,support:support.p,resistance:resistance.p,supportStrength:medB?(support.p*support.q)/medB:1,resistanceStrength:medA?(resistance.p*resistance.q)/medA:1}}
  function fillBuy(asks,bank){const quoteBudget=bank/(1+FEE);let rem=quoteBudget,cost=0,qty=0;for(const l of asks){const cap=l.p*l.q,t=Math.min(rem,cap);if(t<=0)break;qty+=t/l.p;cost+=t;rem-=t;if(rem<=1e-7)break}if(rem>Math.max(.01,quoteBudget*.001)||qty<=0)return null;const avgEntry=cost/qty,buyFee=cost*FEE;return{qty,avgEntry,buyFee,total:cost+buyFee}}
  function bankPlan(bank,bm,target,stop){const f=fillBuy(bm.asks,bank);if(!f)return{bank,valid:false,net:-999,rr:-99,reason:'Not enough visible ask liquidity'};const slip=Math.max(0,(f.avgEntry-bm.ask)/bm.ask),exitDrag=Math.max(bm.spread/2,slip*.7),exit=target*(1-exitDrag),gross=f.qty*exit,sellFee=gross*FEE,net=gross-sellFee-bank,stopExit=stop*(1-exitDrag),stopNet=f.qty*stopExit*(1-FEE),loss=Math.max(0,bank-stopNet),rr=loss>0?net/loss:0,be=f.avgEntry*(1+FEE)/(1-FEE);return{bank,valid:true,net,loss,rr,qty:f.qty,entry:f.avgEntry,slip,breakEven:be,edgePct:net/bank}}
  function directionFor(mins,bm,cm,t,hist){const rsiBias=clamp((cm.rsi-50)/35,-1,1),dayBias=clamp(t.chg/.10,-1,1),h24=clamp((hist?.ret24||0)/.08,-1,1),h7=clamp((hist?.ret7d||0)/.18,-1,1),h30=clamp((hist?.ret30d||0)/.35,-1,1);if(mins===1)return clamp(.48*bm.imb+.27*clamp(cm.trend1/.004,-1,1)+.10*clamp(cm.trend5/.01,-1,1)+.10*rsiBias+.05*h24,-1,1);if(mins===5)return clamp(.36*bm.imb+.22*clamp(cm.trend5/.012,-1,1)+.12*clamp(cm.trend15/.025,-1,1)+.10*rsiBias+.10*h24+.06*h7+.04*dayBias,-1,1);return clamp(.24*bm.imb+.16*clamp(cm.trend5/.012,-1,1)+.18*clamp(cm.trend15/.025,-1,1)+.08*rsiBias+.12*h24+.12*h7+.07*h30+.03*dayBias,-1,1)}
  function horizonTarget(bm,cm,direction,quality,mins,hist){const trend=mins===1?cm.trend1:mins===5?cm.trend5:cm.trend15,histMove=hist?.hourAbs90||0,exp=clamp(hist?.expansion||1,.65,2.2),floor=mins===1?.0007:mins===5?.0015:.003,cap=mins===1?.018:mins===5?.04:.075,scaledHist=histMove*Math.sqrt(mins/60)*exp,base=Math.max(floor,cm.atr*Math.sqrt(mins)*.68,Math.abs(trend)*.58,scaledHist*.75),move=clamp(base*(.52+Math.max(0,direction)*1.08)*(.80+quality*.42),floor*.7,cap);let target=bm.mid*(1+move);if(bm.resistance>bm.mid*1.0006&&bm.resistance<target&&bm.resistanceStrength>=2.2)target=bm.resistance;return{target,move:(target/bm.mid)-1}}
  function rank(plan,bullish,strength,quality,hist){if(!plan.valid||!bullish)return 0;const edge=clamp(plan.edgePct/.02,-1,1),rr=clamp(plan.rr/2,0,1),slipPenalty=clamp(plan.slip/.01,0,1)*18,expBonus=hist?clamp((hist.expansion-1)*12,-8,12):0;return Math.round(clamp(strength*.50+quality*100*.20+Math.max(0,edge)*100*.18+rr*100*.12+expBonus-(plan.net<=0?30:0)-slipPenalty,0,100))}
  async function analyzeCandidate(t){const id=encodeURIComponent(t.id),[book,candles,hist]=await Promise.all([jfetch(`${API}/products/${id}/book?level=2`),jfetch(`${API}/products/${id}/candles?granularity=60`),fetchHourly30(t.id)]),bm=bookMetrics(book),cm=candleMetrics(candles);if(!bm||!cm)return null;const hollow=bm.top5<.12?.55:bm.top5<.22?.75:bm.top5<.35?.9:1,spreadQ=clamp(1-bm.spread/.008,0,1),depthQ=clamp((Math.log10(bm.depth+1)-3.8)/3,0,1),overheat=cm.rsi>82?.72:cm.rsi<18?.82:1,historyQ=hist?clamp(hist.bars/600,0,1):.35,quality=clamp(.27*hollow+.23*spreadQ+.20*depthQ+.15*clamp(Math.log10(t.quoteVol+1)/8,0,1)+.15*historyQ,0,1)*overheat,d1=directionFor(1,bm,cm,t,hist),d5=directionFor(5,bm,cm,t,hist),d15=directionFor(15,bm,cm,t,hist),h1=horizonTarget(bm,cm,d1,quality,1,hist),h5=horizonTarget(bm,cm,d5,quality,5,hist),h15=horizonTarget(bm,cm,d15,quality,15,hist),downside=Math.max(cm.atr*1.8,.005);let stop=bm.mid*(1-downside);if(bm.support<bm.mid&&bm.support>stop&&bm.supportStrength>=2.2)stop=bm.support*(1-.0015);return{id:t.id,price:bm.mid,quality,spread:bm.spread,imb:bm.imb,atr:cm.atr,rsi:cm.rsi,quoteVol:t.quoteVol,bm,cm,hist,stop,h1,h5,h15,d1,d5,d15}}
  function planFor(x,amount,mins){const h=mins===1?x.h1:mins===5?x.h5:x.h15,d=mins===1?x.d1:mins===5?x.d5:x.d15,p=bankPlan(amount,x.bm,h.target,x.stop),strength=clamp(Math.abs(d)*100*x.quality,0,100);p.score=rank(p,d>.10,strength,x.quality,x.hist);p.target=h.target;p.move=h.move;p.direction=d;return p}
  function evaluateRows(rows,amount){return rows.map(x=>({...x,p1:planFor(x,amount,1),p5:planFor(x,amount,5),p15:planFor(x,amount,15)}))}
  function viable(p){return p&&p.valid&&p.net>0&&p.score>=55&&p.rr>=.80}
  function bestFor(rows,key){return [...rows].sort((a,b)=>b[key].score-a[key].score||b[key].net-a[key].net)[0]}
  function renderResults(rows){lastRows=rows;const amount=selectedAmount(),rated=evaluateRows(rows,amount),cands=[['p1',1],['p5',5],['p15',15]].map(([k,m])=>({x:bestFor(rated,k),k,m})).filter(z=>z.x),best=[...cands].sort((a,b)=>b.x[b.k].score-a.x[a.k].score||b.x[b.k].net-a.x[a.k].net).find(z=>viable(z.x[z.k])),hasGood=!!best;if($s('bestCustom'))$s('bestCustom').textContent=`Scanning ${amountLabel(amount)} at 1m / 5m / 15m`;if($s('suggestedAmount'))$s('suggestedAmount').textContent=hasGood?`${amountLabel(amount)} • ${best.m} MIN`:'SKIP FOR NOW';if($s('suggestedWhy'))$s('suggestedWhy').textContent=hasGood?`${best.x.id} projects ${money(best.x[best.k].net)} after estimated fees and size-aware slippage over ${best.m} minute${best.m===1?'':'s'}. 30-day regime: ${pct(best.x.hist?.ret30d||0)}; recent volatility expansion ${(best.x.hist?.expansion||1).toFixed(2)}× normal.`:`At ${amountLabel(amount)}, none of the current finalists has enough projected 1m, 5m or 15m price expansion to clear estimated round-trip costs and risk.`;for(const [id,amt] of [['best50',50],['best100',100],['best150',150]])if($s(id)){const rr=evaluateRows(rows,amt),all=[['p1',1],['p5',5],['p15',15]].map(([k,m])=>({x:bestFor(rr,k),k,m})).filter(z=>z.x).sort((a,b)=>b.x[b.k].score-a.x[a.k].score),b=all[0];$s(id).textContent=b?`${b.x.id} • ${b.m}m • ${money(b.x[b.k].net)} • ${b.x[b.k].score}/100`:'No candidate'}const combined=[...rated].sort((a,b)=>Math.max(b.p1.score,b.p5.score,b.p15.score)-Math.max(a.p1.score,a.p5.score,a.p15.score)).slice(0,8);if($s('scanList'))$s('scanList').innerHTML=combined.map((x,i)=>{const o1=viable(x.p1),o5=viable(x.p5),o15=viable(x.p15),action=o1||o5||o15?'VIABLE / WATCH':'WAIT',hist=x.hist;return `<div class="scanrow"><b>${i+1}. ${x.id}</b> — ${action}<br><span class="small">${amountLabel(amount)} • 1m ${money(x.p1.net)} / ${x.p1.score} ${o1?'✓':'✕'} • 5m ${money(x.p5.net)} / ${x.p5.score} ${o5?'✓':'✕'} • 15m ${money(x.p15.net)} / ${x.p15.score} ${o15?'✓':'✕'}<br>Targets: 1m ${px(x.p1.target)} • 5m ${px(x.p5.target)} • 15m ${px(x.p15.target)} • RSI ${x.rsi.toFixed(1)} • ATR ${(x.atr*100).toFixed(2)}% • slip ${(Math.max(x.p1.slip||0,x.p5.slip||0,x.p15.slip||0)*100).toFixed(3)}%<br>30d ${pct(hist?.ret30d||0)} • 7d ${pct(hist?.ret7d||0)} • 24h ${pct(hist?.ret24||0)} • volatility expansion ${(hist?.expansion||1).toFixed(2)}× • historical 90th-percentile hourly move ${pct(hist?.hourAbs90||0)}</span><br><button class="usepair" data-pair="${x.id}">USE ${x.id}</button></div>`}).join('');document.querySelectorAll('.usepair').forEach(btn=>btn.onclick=()=>usePair(btn.dataset.pair));if($s('scanTime'))$s('scanTime').textContent=`Last full scan: ${new Date().toLocaleTimeString()} • ${amountLabel(amount)} • 1m / 5m / 15m • 30-day regime`;setStatus(hasGood?`BEST ${best.m}M: ${best.x.id} • ${money(best.x[best.k].net)}`:'NO CURRENT 1M / 5M / 15M EDGE AFTER COSTS',hasGood?'good':'warn')}
  function usePair(pair){if($s('pair'))$s('pair').value=pair;if($s('start'))$s('start').click();if($s('scanPicked'))$s('scanPicked').textContent=`Loaded ${pair} into the live forecast below.`}
  async function detailedScan(force=false){if(scanning)return;if(!force&&Date.now()-lastDetailed<45000)return;scanning=true;lastDetailed=Date.now();try{const cands=preCandidates();if(!cands.length){setStatus(`COLLECTING LIVE PRICES — ${tickers.size}/${products.length} pairs heard from`,'warn');return}setStatus(`CHECKING ${cands.length} FINALISTS: 1M / 5M / 15M + 30-DAY HISTORY…`,'warn');const out=[];for(let i=0;i<cands.length;i++){if($s('scanProgress'))$s('scanProgress').textContent=`Deep analysis ${i+1}/${cands.length}: ${cands[i].id} — live book + 1m candles + 30d hourly history`;try{const x=await analyzeCandidate(cands[i]);if(x)out.push(x)}catch{}await sleep(180)}if(!out.length){setStatus('SCAN COULD NOT GET DETAILED MARKET DATA','bad');return}renderResults(out);if($s('scanProgress'))$s('scanProgress').textContent=`Scanned ${products.length} live USD pairs; deep-tested ${out.length} finalists across 1m / 5m / 15m with 30-day history.`}finally{scanning=false}}
  async function launchScan(){try{setStatus('FRESH STARTUP SCAN — LOADING EVERY USD PAIR…','warn');await loadProducts();openTickerSocket();for(let i=0;i<6;i++){await sleep(1000);if($s('scanProgress'))$s('scanProgress').textContent=`Live prices received: ${tickers.size}/${products.length}`;if(tickers.size>=Math.min(products.length,80))break}await detailedScan(true);warmHistoryUniverse();clearInterval(refreshTimer);refreshTimer=setInterval(()=>detailedScan(false),60000)}catch(e){setStatus(`SCANNER ERROR — ${e.message}`,'bad')}}
  if($s('rescanAll'))$s('rescanAll').onclick=()=>detailedScan(true);document.querySelectorAll('.bank').forEach(btn=>btn.addEventListener('click',()=>setTimeout(()=>lastRows.length?renderResults(lastRows):detailedScan(true),0)));if($s('custom')){let t;$s('custom').addEventListener('input',()=>{clearTimeout(t);t=setTimeout(()=>lastRows.length?renderResults(lastRows):detailedScan(true),250)})}window.addEventListener('beforeunload',closeSocket);launchScan();
})();