(()=>{
  const $s=id=>document.getElementById(id);
  const API='https://api.exchange.coinbase.com',WS='wss://advanced-trade-ws.coinbase.com';
  const FEE=.006,DETAIL_COUNT=18;
  const tickers=new Map();let products=[],sock=null,scanning=false,lastDetailed=0,refreshTimer=null,lastRows=[];
  const sleep=ms=>new Promise(r=>setTimeout(r,ms)),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const median=a=>{if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
  const money=n=>Number.isFinite(n)?`${n>=0?'+':'-'}$${Math.abs(n).toFixed(2)}`:'—';
  const px=n=>{if(!Number.isFinite(n)||n<=0)return'—';const a=Math.abs(n),d=clamp(7-Math.floor(Math.log10(a)),2,12);return n.toFixed(d)};
  async function jfetch(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
  function setStatus(text,cls='warn'){const el=$s('scanStatus');if(el){el.textContent=text;el.className='signal '+cls}}
  function selectedAmount(){const custom=+$s('custom')?.value;if(custom>0)return custom;const active=document.querySelector('.bank.active');return +(active?.dataset.bank||50)}
  function amountLabel(n){return '$'+Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}

  async function loadProducts(){const rows=await jfetch(`${API}/products`);products=rows.filter(p=>p.quote_currency==='USD'&&p.status==='online'&&!p.trading_disabled&&!p.cancel_only&&!p.post_only);if($s('scanUniverse'))$s('scanUniverse').textContent=`${products.length} live Coinbase USD pairs`;return products}
  function closeSocket(){if(sock){try{sock.close()}catch{}sock=null}}
  function openTickerSocket(){closeSocket();tickers.clear();sock=new WebSocket(WS);sock.onopen=()=>{const ids=products.map(p=>p.id);for(let i=0;i<ids.length;i+=75)sock.send(JSON.stringify({type:'subscribe',channel:'ticker',product_ids:ids.slice(i,i+75)}))};sock.onmessage=e=>{try{const j=JSON.parse(e.data);for(const ev of j.events||[])for(const t of ev.tickers||[]){const price=+t.price,bid=+t.best_bid,ask=+t.best_ask,vol=+t.volume_24_h,chg=(+t.price_percent_chg_24_h||0)/100;if(price>0)tickers.set(t.product_id,{id:t.product_id,price,bid,ask,vol,chg,t:Date.now()})}}catch{}};sock.onerror=()=>setStatus('SCANNER CONNECTION PROBLEM — retrying','bad');sock.onclose=()=>{if(products.length)setTimeout(()=>{if(!sock||sock.readyState===WebSocket.CLOSED)openTickerSocket()},2500)}}
  function preCandidates(){const now=Date.now(),rows=[];for(const p of products){const t=tickers.get(p.id);if(!t||now-t.t>45000)continue;const mid=(t.bid>0&&t.ask>=t.bid)?(t.bid+t.ask)/2:t.price,spread=t.bid>0&&t.ask>=t.bid?(t.ask-t.bid)/mid:.02,quoteVol=t.price*Math.max(0,t.vol);if(quoteVol<25000||spread>.012)continue;const liq=clamp((Math.log10(quoteVol+1)-4.4)/3.4,0,1),motion=clamp(Math.abs(t.chg)/.12,0,1),spreadQ=clamp(1-spread/.012,0,1),positive=t.chg>0?.08:0;rows.push({...t,quoteVol,spread,pre:.55*liq+.22*motion+.23*spreadQ+positive})}return rows.sort((a,b)=>b.pre-a.pre).slice(0,DETAIL_COUNT)}
  function candleMetrics(raw){const c=(raw||[]).map(x=>({t:+x[0],l:+x[1],h:+x[2],o:+x[3],c:+x[4],v:+x[5]})).sort((a,b)=>a.t-b.t);if(c.length<20)return null;const last=c.at(-1),close=c.map(x=>x.c),trend5=(last.c-close[Math.max(0,close.length-6)])/close[Math.max(0,close.length-6)],trend15=(last.c-close[Math.max(0,close.length-16)])/close[Math.max(0,close.length-16)];let gains=0,losses=0;for(let i=close.length-14;i<close.length;i++){const d=close[i]-close[i-1];if(d>=0)gains+=d;else losses-=d}const rsi=losses===0?100:100-100/(1+(gains/14)/(losses/14));let tr=0;for(let i=c.length-14;i<c.length;i++)tr+=Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c));return{last:last.c,trend5,trend15,rsi,atr:(tr/14)/last.c}}
  function bookMetrics(j){const bids=(j.bids||[]).slice(0,120).map(x=>({p:+x[0],q:+x[1]})).filter(x=>x.p>0&&x.q>0),asks=(j.asks||[]).slice(0,120).map(x=>({p:+x[0],q:+x[1]})).filter(x=>x.p>0&&x.q>0);if(!bids.length||!asks.length)return null;const bid=bids[0].p,ask=asks[0].p,mid=(bid+ask)/2,spread=(ask-bid)/mid,bn=bids.slice(0,50).map(x=>x.p*x.q),an=asks.slice(0,50).map(x=>x.p*x.q),bd=bn.reduce((s,x)=>s+x,0),ad=an.reduce((s,x)=>s+x,0),imb=(bd-ad)/(bd+ad||1),top5=(bn.slice(0,5).reduce((s,x)=>s+x,0)+an.slice(0,5).reduce((s,x)=>s+x,0))/(bd+ad||1),medB=median(bn),medA=median(an),support=bids.filter(x=>x.p>=mid*.985).sort((a,b)=>(b.p*b.q)-(a.p*a.q))[0]||bids[0],resistance=asks.filter(x=>x.p<=mid*1.015).sort((a,b)=>(b.p*b.q)-(a.p*a.q))[0]||asks[0];return{bids,asks,bid,ask,mid,spread,imb,top5,depth:bd+ad,support:support.p,resistance:resistance.p,supportStrength:medB?(support.p*support.q)/medB:1,resistanceStrength:medA?(resistance.p*resistance.q)/medA:1}}
  function fillBuy(asks,bank){const quoteBudget=bank/(1+FEE);let rem=quoteBudget,cost=0,qty=0;for(const l of asks){const cap=l.p*l.q,t=Math.min(rem,cap);if(t<=0)break;qty+=t/l.p;cost+=t;rem-=t;if(rem<=1e-7)break}if(rem>Math.max(.01,quoteBudget*.001)||qty<=0)return null;const avgEntry=cost/qty,buyFee=cost*FEE;return{qty,avgEntry,buyFee,total:cost+buyFee,filledPct:(quoteBudget-rem)/quoteBudget}}
  function bankPlan(bank,bm,target,stop){const f=fillBuy(bm.asks,bank);if(!f)return{bank,valid:false,net:-999,rr:-99,reason:'Not enough visible ask liquidity'};const entrySlip=Math.max(0,(f.avgEntry-bm.ask)/bm.ask),exitDrag=Math.max(bm.spread/2,entrySlip*.7),exit=target*(1-exitDrag),gross=f.qty*exit,sellFee=gross*FEE,net=gross-sellFee-bank,stopExit=stop*(1-exitDrag),stopNet=f.qty*stopExit*(1-FEE),loss=Math.max(0,bank-stopNet),rr=loss>0?net/loss:0,be=f.avgEntry*(1+FEE)/(1-FEE),edgePct=bank>0?net/bank:0;return{bank,valid:true,net,loss,rr,qty:f.qty,entry:f.avgEntry,slip:entrySlip,breakEven:be,edgePct}}
  function horizonTarget(bm,cm,direction,quality,mins){const trend=mins===5?cm.trend5:cm.trend15,base=Math.max(mins===5?.0015:.003,cm.atr*Math.sqrt(mins)*.72,Math.abs(trend)*.60),move=clamp(base*(.55+Math.max(0,direction)*1.05)*(.82+quality*.38),mins===5?.001:.002,mins===5?.035:.06);let target=bm.mid*(1+move);if(bm.resistance>bm.mid*1.001&&bm.resistance<target&&bm.resistanceStrength>=2.2)target=bm.resistance;return{target,move:(target/bm.mid)-1}}
  function rank(plan,bullish,strength,quality){if(!plan.valid||!bullish)return 0;const edge=clamp(plan.edgePct/.02,-1,1),rr=clamp(plan.rr/2,0,1),slipPenalty=clamp(plan.slip/.01,0,1)*18;return Math.round(clamp(strength*.52+quality*100*.20+Math.max(0,edge)*100*.18+rr*100*.10-(plan.net<=0?30:0)-slipPenalty,0,100))}
  async function analyzeCandidate(t){const id=encodeURIComponent(t.id),[book,candles]=await Promise.all([jfetch(`${API}/products/${id}/book?level=2`),jfetch(`${API}/products/${id}/candles?granularity=60`)]),bm=bookMetrics(book),cm=candleMetrics(candles);if(!bm||!cm)return null;const rsiBias=clamp((cm.rsi-50)/35,-1,1),dayBias=clamp(t.chg/.10,-1,1),direction=clamp(.40*bm.imb+.23*clamp(cm.trend5/.01,-1,1)+.17*clamp(cm.trend15/.02,-1,1)+.12*rsiBias+.08*dayBias,-1,1),hollow=bm.top5<.12?.55:bm.top5<.22?.75:bm.top5<.35?.9:1,spreadQ=clamp(1-bm.spread/.008,0,1),depthQ=clamp((Math.log10(bm.depth+1)-3.8)/3,0,1),overheat=cm.rsi>78?.75:cm.rsi<22?.82:1,quality=clamp(.34*hollow+.26*spreadQ+.22*depthQ+.18*clamp(Math.log10(t.quoteVol+1)/8,0,1),0,1)*overheat,bullish=direction>.12,strength=clamp(Math.abs(direction)*100*quality,0,100),h5=horizonTarget(bm,cm,direction,quality,5),h15=horizonTarget(bm,cm,direction,quality,15),downside=Math.max(cm.atr*1.8,.005);let stop=bm.mid*(1-downside);if(bm.support<bm.mid&&bm.support>stop&&bm.supportStrength>=2.2)stop=bm.support*(1-.0015);return{id:t.id,price:bm.mid,direction,quality,strength,spread:bm.spread,imb:bm.imb,atr:cm.atr,rsi:cm.rsi,trend5:cm.trend5,trend15:cm.trend15,quoteVol:t.quoteVol,bm,stop,h5,h15,bullish}}
  function planFor(x,amount,mins){const h=mins===5?x.h5:x.h15,p=bankPlan(amount,x.bm,h.target,x.stop);p.score=rank(p,x.bullish,x.strength,x.quality);p.target=h.target;p.move=h.move;return p}
  function evaluateRows(rows,amount){return rows.map(x=>({...x,p5:planFor(x,amount,5),p15:planFor(x,amount,15)}))}
  function viable(p){return p.valid&&p.net>0&&p.score>=55&&p.rr>=.85}
  function bestFor(rows,key){return [...rows].sort((a,b)=>b[key].score-a[key].score||b[key].net-a[key].net)[0]}
  function renderResults(rows){lastRows=rows;const amount=selectedAmount(),rated=evaluateRows(rows,amount),best5=bestFor(rated,'p5'),best15=bestFor(rated,'p15'),best=viable(best5?.p5)&&(!viable(best15?.p15)||best5.p5.score>=best15.p15.score)?{x:best5,p:best5.p5,mins:5}:{x:best15,p:best15?.p15,mins:15},hasGood=best?.x&&viable(best.p);if($s('best50')){const r=evaluateRows(rows,50),b=bestFor(r,'p15');$s('best50').textContent=b?`${b.id} • ${money(b.p15.net)} / 15m • score ${b.p15.score}/100`:'No candidate'}if($s('best100')){const r=evaluateRows(rows,100),b=bestFor(r,'p15');$s('best100').textContent=b?`${b.id} • ${money(b.p15.net)} / 15m • score ${b.p15.score}/100`:'No candidate'}if($s('best150')){const r=evaluateRows(rows,150),b=bestFor(r,'p15');$s('best150').textContent=b?`${b.id} • ${money(b.p15.net)} / 15m • score ${b.p15.score}/100`:'No candidate'}if($s('bestCustom'))$s('bestCustom').textContent=`Scanning for ${amountLabel(amount)}`;if($s('suggestedAmount'))$s('suggestedAmount').textContent=hasGood?`${amountLabel(amount)} • ${best.mins} MIN`:'SKIP FOR NOW';if($s('suggestedWhy'))$s('suggestedWhy').textContent=hasGood?`${best.x.id} currently projects ${money(best.p.net)} after estimated fees/slippage over the ${best.mins}-minute window. Entry slippage ${(best.p.slip*100).toFixed(3)}%.`:`At ${amountLabel(amount)}, none of the detailed candidates currently clears estimated round-trip fees, size-aware fill slippage and risk. A larger dollar amount increases dollar profit only when the percentage edge survives those costs.`;const combined=[...rated].sort((a,b)=>Math.max(b.p5.score,b.p15.score)-Math.max(a.p5.score,a.p15.score)).slice(0,8);if($s('scanList'))$s('scanList').innerHTML=combined.map((x,i)=>{const ok5=viable(x.p5),ok15=viable(x.p15),action=ok5||ok15?'VIABLE / WATCH':'WAIT';return `<div class="scanrow" data-pair="${x.id}"><b>${i+1}. ${x.id}</b> — ${action}<br><span class="small">Amount ${amountLabel(amount)} • 5m: ${money(x.p5.net)} net, score ${x.p5.score}/100, target ${px(x.p5.target)} ${ok5?'✓':'✕'} • 15m: ${money(x.p15.net)} net, score ${x.p15.score}/100, target ${px(x.p15.target)} ${ok15?'✓':'✕'} • RSI ${x.rsi.toFixed(1)} • ATR ${(x.atr*100).toFixed(2)}% • entry slip ${(Math.max(x.p5.slip,x.p15.slip)*100).toFixed(3)}%</span><br><button class="usepair" data-pair="${x.id}">USE ${x.id}</button></div>`}).join('');document.querySelectorAll('.usepair').forEach(btn=>btn.onclick=()=>usePair(btn.dataset.pair));if($s('scanTime'))$s('scanTime').textContent=`Last full scan: ${new Date().toLocaleTimeString()} • evaluated ${amountLabel(amount)} at 5m and 15m`;setStatus(hasGood?`BEST ${best.mins}M: ${best.x.id} • ${money(best.p.net)}`:'NO CLEAN PROFIT SETUP FOR THIS AMOUNT RIGHT NOW',hasGood?'good':'warn')}
  function usePair(pair){if($s('pair'))$s('pair').value=pair;if($s('start'))$s('start').click();if($s('scanPicked'))$s('scanPicked').textContent=`Loaded ${pair} into the live forecast below.`}
  async function detailedScan(force=false){if(scanning)return;if(!force&&Date.now()-lastDetailed<45000)return;scanning=true;lastDetailed=Date.now();try{const cands=preCandidates();if(!cands.length){setStatus(`COLLECTING LIVE PRICES — ${tickers.size}/${products.length} pairs heard from`,'warn');return}setStatus(`CHECKING ${cands.length} BEST CANDIDATES FOR 5M / 15M PROFIT…`,'warn');const out=[];for(let i=0;i<cands.length;i++){if($s('scanProgress'))$s('scanProgress').textContent=`Detailed check ${i+1}/${cands.length}: ${cands[i].id}`;try{const x=await analyzeCandidate(cands[i]);if(x)out.push(x)}catch{}await sleep(275)}if(!out.length){setStatus('SCAN COULD NOT GET DETAILED MARKET DATA','bad');return}renderResults(out);if($s('scanProgress'))$s('scanProgress').textContent=`Scanned ${products.length} live USD pairs; deeply checked ${out.length} finalists for 5m / 15m viability.`}finally{scanning=false}}
  async function launchScan(){try{setStatus('FRESH STARTUP SCAN — LOADING EVERY USD PAIR…','warn');await loadProducts();openTickerSocket();for(let i=0;i<6;i++){await sleep(1000);if($s('scanProgress'))$s('scanProgress').textContent=`Live prices received: ${tickers.size}/${products.length}`;if(tickers.size>=Math.min(products.length,80))break}await detailedScan(true);clearInterval(refreshTimer);refreshTimer=setInterval(()=>detailedScan(false),60000)}catch(e){setStatus(`SCANNER ERROR — ${e.message}`,'bad')}}
  if($s('rescanAll'))$s('rescanAll').onclick=()=>detailedScan(true);
  document.querySelectorAll('.bank').forEach(btn=>btn.addEventListener('click',()=>setTimeout(()=>lastRows.length?renderResults(lastRows):detailedScan(true),0)));
  if($s('custom')){let t;$s('custom').addEventListener('input',()=>{clearTimeout(t);t=setTimeout(()=>lastRows.length?renderResults(lastRows):detailedScan(true),250)})}
  window.addEventListener('beforeunload',closeSocket);launchScan();
})();